### ISSUE TITLE
Too many request : public-methods.js:89

### ISSUE THREAD

**Issue by meancoin** [StocksExchange/nodejs-client#1]
Hello,

When "Too Many Requests" error happen the lign 89 start but there is a problem.
err.message doesn't exist and err is null : 

Error message : 
Process crashed with: TypeError: Cannot read property 'message' of null
    at Request._callback (/home/runner/node_modules/stocks-exchange-client/lib/public-methods.js:89:37)
    at Request.self.callback (/home/runner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/runner/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/runner/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)

I think you can change throw new error(err.message) for throw new error(res.statusMessage) or throw new error(body).

For information : 
res.statusMessage: 'Too Many Requests'
body: '{\n    "message": "Too Many Attempts."\n}' }

**Comment by Drengel1990** [comment]
Hello!
https://github.com/StocksExchange/nodejs-client/commit/d2e95149248ee6f940292edc96db75a2561a7bec
Check please!!!
